CREATE SCHEMA ASERRADERO;

USE ASERRADERO;

--	TABLA CON LOS DATOS DE LOS CLIENTES
CREATE TABLE CLIENTE
(
ID_CLIENTE INT AUTO_INCREMENT ,
NOMBRE TEXT(50) NOT NULL ,
DNI INT NOT NULL,
PRIMARY KEY (ID_CLIENTE)
)
;

--	TABLA CON TIPOS DE MADERA Y STOCK DE C/U
CREATE TABLE MADERA
(
ID_MADERA INT AUTO_INCREMENT ,
MADERA TEXT(20) NOT NULL ,
CANTIDAD DECIMAL(8, 2) NOT NULL DEFAULT 0,
PRIMARY KEY (ID_MADERA)
) 
;

--	TABLA CON LAS CARACTERÍSTICAS DE LOS ARTÍCULOS Y CANTIDAD DE MADERA USADA POR C/U
CREATE TABLE ARTICULO
(
ID_ARTICULO INT AUTO_INCREMENT ,
NOMBRE VARCHAR(50) NOT NULL ,
PRECIO DECIMAL(7, 2) NOT NULL ,
MADERA_USADA DECIMAL(4, 2) ,
ID_MADERA INT ,
PRIMARY KEY (ID_ARTICULO) ,
FOREIGN KEY (ID_MADERA) REFERENCES MADERA (ID_MADERA)
) 
;

--	TABLA CON LOS PEDIDOS HECHOS POR CLIENTES
CREATE TABLE PEDIDO
(
ID_PEDIDO INT AUTO_INCREMENT ,
CANTIDAD INT NOT NULL DEFAULT 1 ,
FECHA DATE ,
ID_ARTICULO INT ,
ID_CLIENTE INT,
PRIMARY KEY (ID_PEDIDO) ,
FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULO (ID_ARTICULO) ,
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
) 
;

--	TABLA CON LOS DATOS DE LOS PROVEEDORES
CREATE TABLE PROVEEDOR
(
ID_PROVEEDOR INT AUTO_INCREMENT ,
NOMBRE VARCHAR(40) NOT NULL ,
EMAIL VARCHAR(40) NOT NULL,
TELEFONO VARCHAR(30) NOT NULL,
PRIMARY KEY (ID_PROVEEDOR)
)
;

--	TABLA DE MADERA SUMINISTRADA POR LOS PROVEEDORES
CREATE TABLE SUMINISTROS
(
ID_SUMINISTROS INT AUTO_INCREMENT ,
CANTIDAD DECIMAL(4, 2) NOT NULL,
FECHA DATE ,
COSTO DECIMAL(7, 2) NOT NULL ,
ID_PROVEEDOR INT ,
ID_MADERA INT ,
PRIMARY KEY (ID_SUMINISTROS) ,
FOREIGN KEY (ID_MADERA) REFERENCES MADERA (ID_MADERA) ,
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (ID_PROVEEDOR)
) 
;